schema: schema.json
extensions:
  endpoints:
    Default GraphQL Endroint:
      url: https://cms-cache.ubisoft.com/GraphQL/content/v1/spaces/p0f8o8d25gmk
      headers:
        Ubi-Appid: 685a3038-2b04-47ee-9c5a-6403381a46aa
        Ubi-Appname: RainbowSixSiege
        Authorization: Bearer pYflq4nCMNCwz7yxsA1k7UNg1E7SQCRjI4PtDUpsOeg
      introspect: false
